### PR TITLE
Upgrade webpacker and make it work on Cloud9

### PR DESCRIPTION
**Pull request by jgaskins**
While pairing with @Elishebawiggins on her Cloud9 VM, we noticed a _lot_ of extra work had to be done to get things working there:

- Cloud9 only allows a very specific port range: 8080-8082
- Rails runs on 3000 by default
- `webpack-dev-server` runs on 8080, but C9 expects 8080 to be the main web app
- Rails needs to have a hostname (not an IP address) to generate the `<script src>` URL, but `webpack-dev-server` needed to bind to `0.0.0.0` (not a hostname) and they use the same config option

A solution we discussed was to use [`foreman`](https://github.com/ddollar/foreman), but apparently webpacker 1.2 doesn't let us use environment variables in the YAML config the way `database.yml` does. Unfortunately, the webpack host needed to be dynamic.

This PR is the best solution I could find — it's basically just an upgrade of `webpacker` and some tweaked default config options. I created an account on Cloud9 to verify this branch works there (and added some workarounds to the `README` for things that didn't "just work") as well as deleted the entire app (DB and all) from my local machine to verify it works from scratch locally, too.

But once the instructions in the README were followed, `rails s` is all that's needed to run this both locally _and_ on Cloud9. No separate `webpack-dev-server` process (I mean, I'm sure it runs, but Rails handles it and we don't need to care about it).

### CODE REVIEW

**Comment by pollygee** [comment]
@jgaskins what's the status with this?

**Comment by jgaskins** [comment]
It's good to go. I'm not sure why one of the builds is failing. I addressed the failure in 584f1f8 in this PR.

**Comment by pollygee** [comment]
OK @jgaskins I don't want to merge the code that breaks the build.  When you have a chance can you take a look at it please?  @bkemper  did you ever look at the code?

**Comment by jgaskins** [comment]
That's what I meant by addressing the failure:
> I addressed the failure in 584f1f8 in this PR.

The failure in CI:

```
$ RAILS_ENV=development rake db:setup db:drop
rake aborted!
Gem::LoadError: You have already activated rake 12.0.0, but your Gemfile requires rake 12.1.0. Prepending `bundle exec` to your command may solve this.
```

The fix is [already in this PR](https://github.com/rubyforgood/pantry_scheduler/pull/112/files#diff-354f30a63fb0907d4ad57269548329e3R9). Gem version mismatches are due to the build server running a different version of Rake than we have in our Gemfile — the `rake` command loads the `rake` gem, and then when Rails loads `rake` through [`config/application.rb`](https://github.com/rubyforgood/pantry_scheduler/blob/584f1f8ec21250a3d276f69d7d148fbaafc8d43c/config/application.rb#L7), it's a different version. The fix is to run the `rake` command through `bundle exec`, as I did in this PR.

**Pull request closed without merging**
